### ISSUE TITLE
about Texas_super_test.mat

### ISSUE THREAD

**Issue by aiyeshi** [llu025/Heterogeneous_CD#1]
Dear Dr.Luppino,
How to produce the file Texas_super_test.mat in folder legacy\image regression\GPR_Texas.py?
I did not find the mat file in your code.

**Comment by llu025** [comment]
The code of 
` legacy\image regression\Affinity_matrices.m`, 
` legacy\image regression\GPR.py` and 
` legacy\image regression\RF.py` 
have been updated. Now the first saves the file `Data_and_training_sample.mat` which can be used by the other two.
