### ISSUE TITLE
Texas dataset

### ISSUE THREAD

**Issue by CatalinaCharlotte** [llu025/Heterogeneous_CD#14]
Dear Dr.Luppino
Thank you for sharing your code and dataset! While attempting to access the Texas dataset, I noticed that the provided website is not available. I'm curious to know if the link will be fixed in the future or if there is an alternative method to obtain this dataset. Thank you once again!

**Comment by llu025** [comment]
Hello,

Unfortunately it seems Michele Volpi's webpage is down. I am reaching out to him to see if he is going to fix it, or if he is willing to let me upload the dataset to my webpage. Let me come back to you.

Cheers

**Comment by llu025** [comment]
Hello,

Michele Volpi answered and uploaded the dataset at [this link](https://zenodo.org/record/8046719). Please remember to cite his work as requested at his page. Thank you!
