### ISSUE TITLE
the computation of the prior transformation in the Code_Aligned.py.

### ISSUE THREAD

**Issue by sighdn** [llu025/Heterogeneous_CD#15]
Thank you for sharing your code and dataset! I couldn't find any code for calculating the prior transformation information in Code_Aligned.py. Did I miss something?
![image](https://github.com/llu025/Heterogeneous_CD/assets/140034622/fab8c8df-015a-418e-b432-912849802d40)

**Comment by llu025** [comment]
The operations needed to evaluate the priors are in `change_priors.py`, and the ones used in `Code_Aligned_Autoencoders.py` are imported at the beginning of the file at line 11:

```
from change_priors import Degree_matrix, ztz, image_in_patches
```
