### ISSUE TITLE
A Issue About change_priors.py

### ISSUE THREAD

**Issue by goodgoodstudydaydayupup-RS** [llu025/Heterogeneous_CD#17]
Dear Dr.Luppino,

Sorry to bother you. I want to ask a small issue: Is the change prior calculation of change_priors.py can be understood same as the change prior calculation in your another paper "Deep Image Translation with an Affinity-Based Change Prior for Unsupervised Multimodal Change Detection" TGRS2021? I read change_priors.py and find it shares similar steps with the change prior method in TGRS2021 paper. which paper do you recommend to be cited if I use change_priors.py?

Hope for your reply.

**Comment by goodgoodstudydaydayupup-RS** [comment]
More specifically, I use function "eval_prior" in change_priors.py directly for two remote sensing images, it will calculate and return "D", in my view, this "D" is same as the change prior mentioned in TGRS paper. Is this view is ok?

**Comment by llu025** [comment]
Hello,

Yes, the function is the same for both works. The difference between the TGRS and the TNNLS papers is that the latter uses the function only after several epochs, the former uses the information obtained from the function directly from the start.

Regarding which paper to cite, well, I wouldn't mind if you cited both.. 😉

**Comment by goodgoodstudydaydayupup-RS** [comment]
Oh, that‘s good, it is worth citing both! Thank you!
