### ISSUE TITLE
A question about a priori computation in X-Net.py

### ISSUE THREAD

**Issue by LanJ0402** [llu025/Heterogeneous_CD#18]
Hello author, thank you very much for open-sourcing the code for the TGRS paper, I've encountered some problems in reproducing your work, you mentioned in your paper that the prior is obtained by calculating and then averaging over three different scales, but is the implementation strategy in your actual code inconsistent with the instructions in your paper? 
For example, you are using three images in your code that are zoomed in 2x, the original image, and zoomed out 2x to calculate the prior at a patch_size of 20, but that's what you wrote in your paper
![image](https://github.com/llu025/Heterogeneous_CD/assets/155890230/43672719-ab27-49dc-bb13-1a95337a426c)

I'd like to ask which of these two strategies works better in your work? 
Looking forward to your reply very much!

**Comment by llu025** [comment]
Hello,

Although the paper was published in 2021, the code used to produce the initial results was much older than that and was written in TF version 1.14. In that legacy code (found [here](https://github.com/llu025/Heterogeneous_CD/blob/master/legacy/Deep_Image_Translation/ACE-Net.py#L414)), the prior was computed using zoomed in, normal, and zoomed out images.

In an effort to translate to TF version 2.4, the prior calculation was rewritten (see [here](https://github.com/llu025/Heterogeneous_CD/blob/master/Code-Aligned_Autoencoders/change_priors.py#L243)). In this new version the prior are calculated as stated in the paper.

HOWEVER, I just now realise that the function in the new version of the code does not seem to work the way I intended it. In fact, I realised that the logic inside the for loop (and especially the logic behind the `if i < 0` statement) seems to be flawed. Unfortunately, I do not have the time to fix it at the moment, so I will have to leave the issue open for now.

In any case, if the legacy method works for you, please use that one. I do not expect results to differ much between zooming in and out the images or doubling and halving the value of k (except for larger computational load).

**Comment by LanJ0402** [comment]
OK, I get it, thank you for your reply!
