### ISSUE TITLE
About the Code-Aligned_Autoencoders

### ISSUE THREAD

**Issue by yulisun** [llu025/Heterogeneous_CD#2]
Dear Dr.Luppino,
Can you tell me the excuted environment of these codes and the version of tensorflow ？
Thanks！

**Comment by llu025** [comment]
Sure! The experiment were conducted using the Docker Image _madsadrian/tensorflow:latest_ that can be found at https://hub.docker.com/r/madsadrian/tensorflow/tags (now the link is present in the *ReadMe* file).
It is a Linux image with all the required python packages (tqdm, scipy, pydensecrf, tensorflow-addons, pandas). tensorflow:2.0.0-gpu-py3 was the base image.
