### ISSUE TITLE
an error in file cGAN.py 

### ISSUE THREAD

**Issue by aiyeshi** [llu025/Heterogeneous_CD#4]
Dear Dr.Luppino,
When I ran the program cGAN.py in the folder Code-Aligned_Autoencoders, an error occurred as follows:

    C:/pythoncd/Heterogeneous_CD/Code-Aligned_Autoencoders/cGAN.py:175 _train_step  *
        targets = [item for item in sublist for sublist in targets]

    NameError: name 'sublist' is not defined

Could you tell me how to solve the problem?
Thank you very much!
Aiye

**Comment by llu025** [comment]
Hello,

I am sorry, I am quite busy in this period, I will try to get back to you as soon as I can. In the meantime, I can say this error does not look related to the code itself, but to the interpretation of the code from Python. Which Python version are you using? This code is supposed to be working with Python >=3.6

**Comment by llu025** [comment]
Hello,

I modified the code to solve the issue, there was a mistake in the lists comprehension. Please refer to the last 3 commits to the master branch. Cheers,

Luigi
